["Abu Dhabi	G",
"Afghanistan	C / F",
"Albania	C / F",
"Algeria	C / F",
"American Samoa	A / B / F / I",
"Andorra	C / F",
"Angola	C / F",
"Anguilla A / B",
"Antigua A / B",
"Argentina	C / I",
"Armenia	C / F",
"Aruba	A / B / F",
"Australia	I",
"Austria	C / F",
"Azerbaijan	C / F",
"Azores	A / B / C / F",
"Bahamas	A / B",
"Bahrain	G",
"Balearic Islands	C / F",
"Bangladesh	A / C / D / G",
"Barbados	A / B",
"Belarus	C / F",
"Belgium	C / E",
"Belize	A / B / G",
"Benin	C / E",
"Bermuda	A / B",
"Bhutan	C / D / G",
"Bolivia	A / C",
"Bonaire	A / C",
"Bosnia C / F",
"Botswana	D / G",
"British Virgin Islands	A / B",
"Brunei	G",
"Bulgaria	C / F",
"Burkina Faso	C / E",
"Burma A / C / D / G / I",
"Burundi	C / E",
"Cambodia	A / C / G",
"Cameroon	C / E",
"Canada	A / B",
"Canary Islands	C / E / F",
"Cape Verde C / F",
"Cayman Islands	A / B",
"Central African Republic	C / E",
"Chad	C / E / F",
"Channel Islands C / G",
"Chile	C / L",
"China, People’s Republic of	A / C / I",
"Christmas Island	I",
"Cocos Islands	I",
"Colombia	A / B",
"Comoros	C / E",
"Congo	C / E",
"Cook Islands I",
"Costa Rica	A / B",
"Côte d’Ivoire C / E",
"Croatia	C / F",
"Cuba	A / B / C / L",
"Curaçao	A / B",
"Cyprus	G",
"Czech Republic C / E",
"Denmark	C / E / F / K",
"Djibouti	C / E",
"Dominica	D / G",
"Dominican Republic	A / B / C",
"Dubai G",
"East Timor C / E / F / I",
"Ecuador	A / B",
"Egypt	C / F",
"El Salvador	A / B",
"England	G",
"Equatorial Guinea	C / E",
"Eritrea	C / L",
"Estonia	C / F",
"Ethiopia	C / F / G",
"Faeroe Islands	C / E / F / K",
"Falkland Islands	G",
"Fiji	I",
"Finland	C / F",
"France	C / E",
"French Guiana C / E",
"French Polynesia C / E",
"Gabon C / E",
"Gambia	G",
"Gaza Strip C / H",
"Georgia	C / F",
"Germany	C / F",
"Ghana	D / G",
"Gibraltar	G",
"Great Britain G",
"Greece	C / F",
"Greenland	C / E / F / K",
"Grenada	G",
"Guadeloupe C / E",
"Guam	A / B",
"Guatemala	A / B",
"Guinea	C / F",
"Guinea-Bissau	C / E / F",
"Guyana	A / B / D / G",
"Haiti	A / B",
"Holland C / F",
"Honduras	A / B",
"Hong Kong	G",
"Hungary	C / F",
"Iceland	C / F",
"India	C / D / M",
"Indonesia	C / F",
"Iran	C / F",
"Iraq	C / D / G",
"Ireland G	",
"Isle of Man	C / G",
"Israel	C / H",
"Italy	C / F / L",
"Jamaica	A / B",
"Japan	A / B",
"Jordan	C / D / F / G / J",
"Kazakhstan	C / F",
"Kenya	G",
"Kiribati	I",
"Kosovo	C / F",
"Kuwait	G",
"Kyrgyzstan	C / F",
"Laos	A / B / C / E / F",
"Latvia	C / F",
"Lebanon	C / D / G",
"Lesotho	M",
"Liberia	A / B / C / F",
"Libya	C / L",
"Liechtenstein	C / J",
"Lithuania	C / F",
"Luxembourg	C / F",
"Macau	G",
"Macedonia, North	C / F",
"Madagascar	C / E",
"Madeira	C / F",
"Malawi	G",
"Malaysia	G	",
"Maldives	C / D / G / L",
"Mali	C / E",
"Malta	G",
"Marshall Islands	A / B",
"Martinique C / E",
"Mauritania	C / E / F",
"Mauritius	C / G",
"Mayotte C / E",
"Mexico	A / B",
"Micronesia A / B",
"Moldova	C / F",
"Monaco	C / E / F",
"Mongolia	A / C / F ",
"Montenegro	C / F",
"Montserrat	A / B",
"Morocco	C / E",
"Mozambique	C / F / M",
"Myanmar A / C / D / G / I",
"Namibia	D / M",
"Nauru	I",
"Nepal	C / D / M",
"Netherlands	C / F",
"New Caledonia C / E",
"New Zealand	I",
"Nicaragua	A / B",
"Niger	C / D / E",
"Nigeria	D / G",
"Niue	I",
"Norfolk Island	I",
"North Cyprus G",
"North Korea	C / F",
"North Macedonia	C / F",
"Northern Ireland	G",
"Norway	C / F",
"Oman	G",
"Pakistan	C / D",
"Palau	A / B",
"Palestine	C / H",
"Panama	A / B",
"Papua New Guinea	I",
"Paraguay	A / C",
"Peru	A / B / C",
"Philippines	A / B / C",
"Pitcairn Islands	I",
"Poland	C / E",
"Portugal	C / F",
"Puerto Rico	A / B",
"Qatar	G",
"Réunion C / E",
"Romania	C / F",
"Russia C / F",
"Rwanda	C / E / F / G",
"Saba	A / B",
"Saint Barthélemy C / E",
"Saint Helena	G",
"Saint Kitts and Nevis D / G",
"Saint Lucia	G",
"Saint Martin C / E",
"Saint Pierre C / E",
"Saint Vincent A / B / G	",
"Samoa	I",
"San Marino	C / F / L",
"São Tomé and Príncipe	C / F",
"Saudi Arabia	G",
"Scotland	G",
"Senegal	C / D / E",
"Serbia	C / F",
"Seychelles	G",
"Sierra Leone	D / G",
"Singapore	G",
"Sint Eustatius	A / B / C / F	",
"Sint Maarten	A / B",
"Slovakia	C / E",
"Slovenia	C / F",
"Solomon Islands	G / I",
"Somalia	A / C / G",
"South Africa	C / M / N",
"South Korea	C / F",
"South Sudan	C / D",
"Spain	C / F",
"Sri Lanka	G",
"Sudan	C / D",
"Suriname A / B / C / F	",
"Swaziland	M",
"Sweden	C / F",
"Switzerland	C / J",
"Syria	C / E / L",
"Tahiti C / E",
"Taiwan	A / B",
"Tajikistan	C / F",
"Tanzania	D / G",
"Thailand	A / B / C / O",
"Togo	C / E",
"Tokelau	I",
"Tonga	I",
"Trinidad & Tobago	A / B",
"Tunisia	C / E",
"Turkey	C / F",
"Turkmenistan	C / F",
"Turks and Caicos Islands	A / B",
"Tuvalu	I",
"Uganda	G",
"Ukraine	C / F",
"United Arab Emirates G",
"United Kingdom G",
"United States of America A / B",
"United States Virgin Islands	A / B",
"Uruguay	C / F / L",
"Uzbekistan	C / F",
"Vanuatu	I",
"Vatican City	C / F / L",
"Venezuela	A / B",
"Vietnam	A / B / C",
"Virgin Islands A / B",
"Wales	G",
"Wallis and Futuna C / E",
"West Bank	C / H",
"Western Sahara	C / E",
"Yemen	A / D / G",
"Zambia	C / D / G",
"Zimbabwe 	D / G"]